version: 0.2

phases:
  install:
    commands:
      - echo 'install'
  pre_build:
    commands:
      - echo 'pre_build'
  build:
    commands:
    - echo "HELLO WORLD" > result.txt
  post_build:
    commands:
    - echo 'post_build'
artifacts:
  files:
  - result.txt